; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
; Placa principal no momento: ESP32-S2 Mini (lote C3 com antena inconsistente)
default_envs = esp32s2_mini

[env:esp32c3_supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; Habilita a porta serial nativa via USB-C
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200


[env:esp32s2_mini]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino

; Configurações específicas para ESP32-S2 Mini com ESP32-S2FNR2
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=1

monitor_speed = 115200
